apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-git-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/23Sidhu/done.git  # Replace this URL with your repository URL
  ref:
    branch: main

